version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.1
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
      - ./db/import:/var/lib/neo4j/import
      - ./db/plugins:/plugins
    environment:
      # Authentication using environment variables
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
      
      # APOC configuration
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      
      # Plugins
      NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
      
      # Security settings
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    restart: unless-stopped
    networks:
      - luca-network

  llm-graph-builder:
    image: shivansh371/llm-graph-builder-backend
    container_name: llm-graph-builder-backend
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
    environment:
      # Embedding configuration
      EMBEDDING_MODEL: "openai"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      RAGAS_EMBEDDING_MODEL: "openai"
      IS_EMBEDDING: "TRUE"
      KNN_MIN_SCORE: "0.94"
      
      # Feature flags
      GEMINI_ENABLED: "False"
      GCP_LOG_METRICS_ENABLED: "False"
      
      # Processing configuration
      NUMBER_OF_CHUNKS_TO_COMBINE: "6"
      UPDATE_GRAPH_CHUNKS_PROCESSED: "20"
      CHUNKS_TO_BE_CREATED: "200"
      
      # Neo4j connection (internal docker network)
      NEO4J_URI: "bolt://neo4j:7687"
      NEO4J_USERNAME: "${NEO4J_USER}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
      NEO4J_DATABASE: "neo4j"
      
      # AWS (empty for now)
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      
      # LangChain (empty for now)
      LANGCHAIN_API_KEY: ""
      LANGCHAIN_PROJECT: ""
      LANGCHAIN_TRACING_V2: ""
      LANGCHAIN_ENDPOINT: ""
      
      # Storage configuration
      GCS_FILE_CACHE: "False"
      NEO4J_USER_AGENT: ""
      ENABLE_USER_AGENT: ""
      LLM_MODEL_CONFIG_model_version: ""
      
      # Entity embeddings
      ENTITY_EMBEDDING: "TRUE"
      DUPLICATE_SCORE_VALUE: "0.97"
      DUPLICATE_TEXT_DISTANCE: "3"
      
      # Default model
      DEFAULT_DIFFBOT_CHAT_MODEL: " "
      
      # LLM Model configurations (using OPENAI_API_KEY from .envrc)
      LLM_MODEL_CONFIG_openai_gpt_3.5: "gpt-3.5-turbo-0125,${OPENAI_API_KEY}"
      LLM_MODEL_CONFIG_openai_gpt_4o_mini: "gpt-4o-mini,${OPENAI_API_KEY}"
      LLM_MODEL_CONFIG_openai_gpt_4o: "gpt-4o,${OPENAI_API_KEY}"
      LLM_MODEL_CONFIG_gemini_1.5_pro: "gemini-1.5-pro-002"
      LLM_MODEL_CONFIG_gemini_1.5_flash: "gemini-1.5-flash-002"
      LLM_MODEL_CONFIG_diffbot: "diffbot,diffbot_api_key"
      LLM_MODEL_CONFIG_azure_ai_gpt_35: "azure_deployment_name,azure_endpoint,azure_api_key,api_version"
      LLM_MODEL_CONFIG_azure_ai_gpt_4o: "gpt-4o,https://YOUR-ENDPOINT.openai.azure.com/,azure_api_key,api_version"
      LLM_MODEL_CONFIG_groq_llama3_70b: "model_name,base_url,groq_api_key"
      LLM_MODEL_CONFIG_anthropic_claude_3_5_sonnet: "model_name,anthropic_api_key"
      LLM_MODEL_CONFIG_fireworks_llama_v3_70b: "model_name,fireworks_api_key"
      LLM_MODEL_CONFIG_bedrock_claude_3_5_sonnet: "model_name,aws_access_key_id,aws_secret__access_key,region_name"
      LLM_MODEL_CONFIG_deepseek: "deepseek-r1,http://localhost:11434,http://localhost:11434"
      
      # Additional configuration
      YOUTUBE_TRANSCRIPT_PROXY: "https://user:pass@domain:port"
      EFFECTIVE_SEARCH_RATIO: "5"
      GRAPH_CLEANUP_MODEL: "openai_gpt_4o"
      BEDROCK_EMBEDDING_MODEL: "model_name,aws_access_key,aws_secret_key,region_name"
      LLM_MODEL_CONFIG_bedrock_nova_micro_v1: "model_name,aws_access_key,aws_secret_key,region_name"
      LLM_MODEL_CONFIG_bedrock_nova_lite_v1: "model_name,aws_access_key,aws_secret_key,region_name"
      LLM_MODEL_CONFIG_bedrock_nova_pro_v1: "model_name,aws_access_key,aws_secret_key,region_name"
    restart: unless-stopped
    networks:
      - luca-network

networks:
  luca-network:
    driver: bridge